teveo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.i18n import set_language #manejar rutas que soportan internacionalizacion


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('teveoapp.urls')),
]

teveoapp/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

# Create your models here.
class Camara(models.Model):
    id = models.CharField(max_length=100, primary_key=True)
    src = models.TextField()
    lugar = models.CharField(max_length=300)
    coordenadas = models.CharField(max_length=200)

class Comentario(models.Model):
    camara = models.ForeignKey(Camara, on_delete=models.CASCADE)
    comentador = models.CharField(max_length=100)
    comentario = models.TextField()
    fecha = models.DateTimeField(auto_now_add=True)


class Configuracion(models.Model):
    nombre_usuario = models.CharField(max_length=50, default='Anónimo')
    TAMANO_FUENTE_CHOICES = [
        (10, _('Small')),
        (12, _('Medium')),
        (16, _('Large')),
        (26, _('X-Large'))
    ]
    tamano_fuente = models.IntegerField(choices=TAMANO_FUENTE_CHOICES, default=None)
    TIPO_FUENTE_CHOICES = [
        ('Arial', 'Arial'),
        ('Helvetica', 'Helvetica'),
        ('Monospace', 'Monospace'),
        ('Verdana', 'Verdana'),
        ('Times new roman', 'Times New Roman'),
    ]
    tipo_fuente = models.CharField(max_length=50, choices=TIPO_FUENTE_CHOICES, default=None)


class Like(models.Model):
    megusta = models.ForeignKey(Camara, on_delete=models.CASCADE, default=None)

templates/ayuda.html
{% load static %}
<!--DOCTYPE html-->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TeVeO</title>
    <!--Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Custom styles-->
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <style>
        body {
            font-size: {{ config_actual.tamano_fuente }}px;
            font-family: {{ config_actual.tipo_fuente }};
        }

    </style>
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
</head>
<body>

    <header id="header">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand">TeVeO</a>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item"><a class="nav-link" href="/">Principal</a></li>
                    <li class="nav-item"><a class="nav-link" href="/camaras">Cámaras</a></li>
                    <li class="nav-item"><a class="nav-link" href="/configuracion">Configuración</a></li>
                    <li class="nav-item"><a class="nav-link" href="/help">Ayuda</a></li>
                    <li class="nav-item"><a class="nav-link" href="admin/">Admin</a></li>
                    <li class="nav-item"><a class="nav-link" href="/logout">Cerrar sesión</a></li>
                </ul>
            </div>
        </nav>
    </header>

    <div class="hamburger">
        <div class="_layer -top"></div>
        <div class="_layer -mid"></div>
        <div class="_layer -bottom"></div>
    </div>
    <nav class="menuppal">
        <ul>
            <li class="nav-item"><a class="nav-link" href="/">Principal</a></li>
            <li class="nav-item"><a class="nav-link" href="/camaras">Cámaras</a></li>
            <li class="nav-item"><a class="nav-link" href="/configuracion">Configuración</a></li>
            <li class="nav-item"><a class="nav-link" href="/help">Ayuda</a></li>
            <li class="nav-item"><a class="nav-link" href="admin/">Admin</a></li>
            <li class="nav-item"><a class="nav-link" href="/logout">Cerrar sesión</a></li>
            <div class="username-container">
                <br>
                Bienvenid@, {{ nombre_usuario }}
            </div>
        </ul>
    </nav>

    <div id="main-content">
        <header>
             <h2>Páginas principales de TeVeO:</h2>
        </header>
        <h4>Página principal: "/"</h4>
        <p>En la página principal se ofrecerá un listado de los comentarios puestos, organizados de más nuevos a más viejos, y paginado.</p>
        <details>
            <ul>
                <li>ID de la cámara a la que se refiere (enlace a la página de la cámara)</li>
                <li>Fecha del comentario</li>
                <li>Imagen de la cámara en el momento que se puso el mensaje</li>
            </ul>
        </details>
        <h4>Página de las cámaras: "/camaras"</h4>
        <details>
            <ul>
                <li>Listado de las fuentes de datos disponibles, con un botón junto a cada una de ellas</li>
                <li>Listado de todas las cámaras paginado</li>
            </ul>
        </details>
        <h4>Página de cada cámara: "/id:camara"</h4>
        <details>
            <ul>
                <li>Enlace a la página dinámica de la cámara</li>
                <li>Información de la cámaras: nombre(lugar) y localización (longitud y latitud)</li>
                <li>Imagen actual de la cámara</li>
                <li>Enlace para pasar a la página que permite escribir un comentario para la cámara</li>
                <li>Un listado de todos los comentarios puestos para esa cámara desde cualquier navegador</li>
            </ul>
        </details>
        <h4>Página de comentarios: "/comentarios"</h4>
        <details>
            <ul>
                <li>Información de la cámara</li>
                <li>Imagen de la cámara que se reciba en ese momento</li>
                <li>Fecha</li>
                <li>Hora</li>
                <li>Formulario para poner el texto del comentario</li>
            </ul>
        </details>
        <h4>Página dinámica: "/id:dyn"</h4>
        <p>El nombre de recurso de la página dinámica de cada cámara será el mismo que el de la página de la cámara, con el sufijo -dyn</p>
        <details>
            <ul>
                <li>Solicitar periódicamente (cada 30 segundos) la imagen</li>
                <li>Listado de todas las cámaras paginado</li>
                <li>Actualizar los comentarios para la cámara cada 30s</li>
                <li>Cargar, al pulsar el enlace correspondiente, el formulario que permita poner un comentario</li>
            </ul>
        </details>
        <h4>Página de configuracion: "/configuracion"</h4>
        <p>Permitirá configurar el sitio para ese navegador.</p>
        <details>
            <ul>
                <li>Formulario para elegir el nombre con el que se pondrán los comentarios </li>
                <li>Formulario para elegir los elementos de apariencia personalizables del sitio (tamaño y tipo de la letra)</li>
            </ul>
        </details>

        <h4>Página de ayuda: "/help"</h4>
        <details>
            <ul><li>Autoría de la práctica: Nora Larrañaga García</li></ul>
        </details>
    </div>

    <footer id="footer">
        Cámaras:{{ total_camaras }}. Comentarios: {{ total_comentarios }}.
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script>
         // selector
        var menu = document.querySelector('.hamburger');

        // method
        function toggleMenu (event) {
          this.classList.toggle('is-active');
          document.querySelector( ".menuppal" ).classList.toggle("is_active");
          event.preventDefault();
        }

        // event
        menu.addEventListener('click', toggleMenu, false);
    </script>
</body>
</html>

templates/camara-dyn.html
{% load static %}
<!--DOCTYPE html-->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TeVeO</title>
    <!--Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Custom styles-->
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <style>
        body {
            font-size: {{ config_actual.tamano_fuente }}px;
            font-family: {{ config_actual.tipo_fuente }};
        }
        img {
            width: 50%;
            height: auto;
        }

    </style>
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
</head>
<body>
    <div id="image-container">
        hx-get={% url 'camara_dinamica' id %}"
        hx-trigger="load, every 30s"
        hx-target="#content_embedded"
        hx-swap="innerHTML"
    </div>

    <header id="header">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand">TeVeO</a>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item"><a class="nav-link" href="/">Principal</a></li>
                    <li class="nav-item"><a class="nav-link" href="/camaras">Cámaras</a></li>
                    <li class="nav-item"><a class="nav-link" href="/configuracion">Configuración</a></li>
                    <li class="nav-item"><a class="nav-link" href="/help">Ayuda</a></li>
                    <li class="nav-item"><a class="nav-link" href="admin/">Admin</a></li>
                    <li class="nav-item"><a class="nav-link" href="/logout">Cerrar sesión</a></li>
                </ul>
            </div>
        </nav>
    </header>

    <div class="hamburger">
        <div class="_layer -top"></div>
        <div class="_layer -mid"></div>
        <div class="_layer -bottom"></div>
    </div>
    <nav class="menuppal">
        <ul>
            <li class="nav-item"><a class="nav-link" href="/">Principal</a></li>
            <li class="nav-item"><a class="nav-link" href="/camaras">Cámaras</a></li>
            <li class="nav-item"><a class="nav-link" href="/configuracion">Configuración</a></li>
            <li class="nav-item"><a class="nav-link" href="/help">Ayuda</a></li>
            <li class="nav-item"><a class="nav-link" href="admin/">Admin</a></li>
            <li class="nav-item"><a class="nav-link" href="/logout">Cerrar sesión</a></li>
            <div class="username-container">
                <br>
                Bienvenid@, {{ nombre_usuario }}
            </div>
        </ul>
    </nav>

    <div id="main-content">
        <h2><li>Imagen de la cámara:</li></h2>
        <img src="data:image/jpeg;base64, {{ image_base64 }}" alt="" class="img">
        <br>
        <h2><li>Comentarios de la cámara:</li></h2>
            {% for comment in comentarios %}
                <div>Comentario: {{ comment.comentario }}</div>
            {% endfor %}
        <div><a href="{{ camara.id }}">Accede a la cámara</a></div>
        <a href="/comentario?id={{ id }}">Nuevo comentario: </a>
    </div>

    <footer id="footer">
        Cámaras:{{ total_camaras }}. Comentarios: {{ total_comentarios }}.
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script>
         // selector
        var menu = document.querySelector('.hamburger');

        // method
        function toggleMenu (event) {
          this.classList.toggle('is-active');
          document.querySelector( ".menuppal" ).classList.toggle("is_active");
          event.preventDefault();
        }

        // event
        menu.addEventListener('click', toggleMenu, false);
    </script>
</body>
</html>

templates/camaras.html
{% load static %}
<!--DOCTYPE html-->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TeVeO</title>
    <!--Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Custom styles-->
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <style>
        body {
            font-size: {{ config_actual.tamano_fuente }}px;
            font-family: {{ config_actual.tipo_fuente }};
        }
        img {
            width: 50%;
            height: auto;
        }

    </style>
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
</head>
<body>

    <header id="header">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand">TeVeO</a>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item"><a class="nav-link" href="/">Principal</a></li>
                    <li class="nav-item"><a class="nav-link" href="/camaras">Cámaras</a></li>
                    <li class="nav-item"><a class="nav-link" href="/configuracion">Configuración</a></li>
                    <li class="nav-item"><a class="nav-link" href="/help">Ayuda</a></li>
                    <li class="nav-item"><a class="nav-link" href="admin/">Admin</a></li>
                    <li class="nav-item"><a class="nav-link" href="/logout">Cerrar sesión</a></li>
                </ul>
            </div>
        </nav>
    </header>

    <div class="hamburger">
        <div class="_layer -top"></div>
        <div class="_layer -mid"></div>
        <div class="_layer -bottom"></div>
    </div>
    <nav class="menuppal">
        <ul>
            <li class="nav-item"><a class="nav-link" href="/">Principal</a></li>
            <li class="nav-item"><a class="nav-link" href="/camaras">Cámaras</a></li>
            <li class="nav-item"><a class="nav-link" href="/configuracion">Configuración</a></li>
            <li class="nav-item"><a class="nav-link" href="/help">Ayuda</a></li>
            <li class="nav-item"><a class="nav-link" href="admin/">Admin</a></li>
            <li class="nav-item"><a class="nav-link" href="/logout">Cerrar sesión</a></li>
            <div class="username-container">
                <br>
                Bienvenid@, {{ nombre_usuario }}
            </div>
        </ul>
    </nav>

    <div id="main-content">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    {% if num_camaras is empty %}
                    <h2>Fuentes de Datos</h2>
                            {% for fuente in datos  %}
                                <form action="/camaras" method="post">
                                {% csrf_token %}
                                    <input type="hidden" name="list_url" value="{{ fuente }}">
                                    <div>
                                         <a href="{{ fuente }}">{{ fuente }}</a><input type="submit" value="Descargar">
                                    </div>
                                </form>
                            {% endfor %}
                    {% else %}
                        <img src="{{ imagen_cam }}" alt="">
                        <h2>Lista de cámaras</h2>
                            {% for camara in pag_camaras %}
                                <div class="camera-item">
                                    <p>Camara ID: {{ camara.id }}</p>
                                    <a href="{{ camara.id }}">Accede</a>
                                    <p>Lugar: {{ camara.lugar }}</p>
                                    <p>Coordenadas: {{ camara.coordenadas }}</p>
                                    <div><a href="{{ camara.id }}dyn">Página dinámica de la cámara</a></div>
                                    <div><label>Comentarios: {{ camara.comentario_set.count }}</label></div>
                                    <div><label>Me gusta: {{ camara.like_set.count }}</label></div>
                                    <form action="/camaras" method="POST">
                                    {% csrf_token %}
                                        <input type="hidden" name="id" value="{{ camara.id }}">
                                        <input type="submit" value="Me gusta">
                                    </form>
                                    <br><br>
                                </div>
                            {% endfor %}
                        <h2>Lista de Fuentes de Datos</h2>
                            {% for fuente in datos %}
                                 <form action="/camaras" method="POST">
                                 {% csrf_token %}
                                     <input type="hidden" name="list_url" value="{{ fuente }}">
                                     <div>
                                         <a href="{{ fuente }}">{{ fuente }}</a><input type="submit" value="Descargar">
                                     </div>
                                 </form>
                            {% endfor %}
                    {% endif %}
                    </div>
                    <div aria-label="Page navigation">
                        <ul class="pagination justify-content-center">
                            {% if pag_camaras.has_previous %}
                                <li class="page-item"><a class="page-link d-block" href="?page=1">&laquo; Primera</a></li>
                                <li class="page-item"><a class="page-link" href="?page={{ pag_camaras.previous_page_number }}">Anterior</a></li>
                            {% endif %}
                            <li class="page-item disabled">
                                <span class="page-link">
                                    Página {{ pag_camaras.number }} de {{ pag_camaras.paginator.num_pages }}
                                </span>
                            </li>
                            {% if pag_camaras.has_next %}
                                <li class="page-item"><a class="page-link" href="?page={{ pag_camaras.next_page_number }}">Siguiente</a></li>
                                <li class="page-item"><a class="page-link d-block" href="?page={{ pag_camaras.paginator.num_pages }}">Última &raquo;</a></li>
                            {% endif %}
                        </ul>
                     </div>
                </div>
            </div>
        </div>
    </div>

     <footer id="footer">
        Cámaras:{{ total_camaras }}. Comentarios: {{ total_comentarios }}.
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script>
         // selector
        var menu = document.querySelector('.hamburger');

        // method
        function toggleMenu (event) {
          this.classList.toggle('is-active');
          document.querySelector( ".menuppal" ).classList.toggle("is_active");
          event.preventDefault();
        }

        // event
        menu.addEventListener('click', toggleMenu, false);
    </script>
</body>
</html>

templates/configuracion.html
{% load static %}
{% load i18n %}
<!--DOCTYPE html-->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Custom styles-->
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <style>
        body {
            font-size: {{ config_actual.tamano_fuente }}px;
            font-family: {{ config_actual.tipo_fuente }};
        }
        img {
            width: 50%;
            height: auto;
        }

    </style>
    <link rel="icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
</head>
<body>

    <header id="header">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container">
                <a class="navbar-brand">TeVeO</a>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item"><a class="nav-link" href="/">Principal</a></li>
                    <li class="nav-item"><a class="nav-link" href="/camaras">Cámaras</a></li>
                    <li class="nav-item"><a class="nav-link" href="/configuracion">Configuración</a></li>
                    <li class="nav-item"><a class="nav-link" href="/help">Ayuda</a></li>
                    <li class="nav-item"><a class="nav-link" href="admin/">Admin</a></li>
                    <li class="nav-item"><a class="nav-link" href="/logout">Cerrar sesión</a></li>
                </ul>
            </div>
        </nav>
    </header>

    <div class="hamburger">
        <div class="_layer -top"></div>
        <div class="_layer -mid"></div>
        <div class="_layer -bottom"></div>
    </div>
    <nav class="menuppal">
        <ul>
            <li class="nav-item"><a class="nav-link" href="/">Principal</a></li>
            <li class="nav-item"><a class="nav-link" href="/camaras">Cámaras</a></li>
            <li class="nav-item"><a class="nav-link" href="/configuracion">Configuración</a></li>
            <li class="nav-item"><a class="nav-link" href="/help">Ayuda</a></li>
            <li class="nav-item"><a class="nav-link" href="admin/">Admin</a></li>
            <li class="nav-item"><a class="nav-link" href="/logout">Cerrar sesión</a></li>
            <div class="username-container">
                <br>
                Bienvenid@, {{ config_actual.nombre_usuario }}
            </div>
        </ul>
    </nav>
    <div id="main-content">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h3>Nueva configuración:</h3>
                    <div style="border: 1px solid #000; padding: 10px; margin-bottom: 20px;">
                        <form action="" method="POST">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit">Guardar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="column justify-content-center">
                <p>Configuración actual:</p>
                <div style="border: 1px solid #000; padding: 10px;">
                    <p><strong>Nombre:</strong> {{ config_actual.nombre_usuario}}</p>
                    <p><strong>Tamaño de fuente:</strong> {{ config_actual.get_tamano_fuente_display }}</p>
                    <p><strong>Tipo de fuente:</strong> {{ config_actual.get_tipo_fuente_display }}</p>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="column justify-content-center">
            <p class="column justify-content-center">Autoriza a otro navegador a acceder al sitio con la misma configuración:</p>
        </div>
         <div class="column justify-content-center">
            <a class="bg-success text-white column justify-content-center" href="{% url 'autorizar_navegador' %}?session_key={{ session_key }}">Autorización</a>
         </div>
    </div>
    <br>
    <footer id="footer">
        Cámaras: {{ total_camaras }}. Comentarios: {{ total_comentarios }}.
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script>
         // selector
        var menu = document.querySelector('.hamburger');

        // method
        function toggleMenu (event) {
          this.classList.toggle('is-active');
          document.querySelector( ".menuppal" ).classList.toggle("is_active");
          event.preventDefault();
        }

        // event
        menu.addEventListener('click', toggleMenu, false);
    </script>
</body>
</html>